sudo: required

services:
    - docker
    
script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ fedora:latest /bin/sh -c "dnf update"
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ fedora:latest /bin/sh -c "autoreconf -ifv && configure && make check"
